### ISSUE TITLE
Rook deployment and command namespace discrepancy

### ISSUE THREAD

**Issue by GaruGaru** [hobby-kube/guide#45] opened 2018-05-07 14:31 UTC
In the rook documentation the operator is deployed on the default namespace
```yaml
metadata:
  name: rook-operator
  namespace: default
```
But in the docs the check command uses the rook namespace 

`kubectl -n rook get pods`

**Comment by pstadler** [comment] 2018-05-07 16:02
I'm not sure what's best practice. Maybe @galexrt could chime in?

**Comment by galexrt** [comment] 2018-05-08 06:14
@pstadler @GaruGaru The operator should be deployed in `rook-system` (or any other namespace) (that should also has been clarified in the lastet master documentation) because it will create certain objects in it to keep track of PV mounts, etc which should not simply be deleted.
The example cluster namespace is `rook`.

Staying "true" to the defaults should be the "right way" here though to keep it simple for any debugging ;)

**Comment by galexrt** [comment] 2018-05-08 12:40
@pstadler Separated namespaces may not apply to your specific use case of only one storage backend (e.g. Ceph) used here, though for people potentially using another storage "backend" (e.g. upcoming Minio and/or CockroachDB) it is recommended to use separate namespaces. This is also caused by the current limitation of being able to create/deploy only one storage backend per namespace.

**Example namespace list when using more than one storage backend/cluster**:
* Namespace for Rook operator(s) `rook-system`
* Namespace for Ceph Cluster SSD `ceph-ssd`
* Namespace for Ceph Cluster HDD `ceph-hdd`
* Namespace for Minio 1 namespace `minio-1`

If you only use one storage backend (e.g. just Ceph), you can put the operator and cluster (aka storage backend) into one namespace together, though I personally would just use two namespaces as they should not hurt the performance of Kubernetes.
At least I know of a clusters with more than 100+ namespaces and not having a problem with latency because of it.

**Comment by pstadler** [comment] 2018-05-23 11:34
This is now fixed.

**Closed by pstadler** 2018-05-23 11:34 UTC
Labels: storage
